spring:
  application:
    name: SmsMultiSenderLib

mobildev:
  sms:
    url: "https://xmlapi.mobildev.com"
    username: "5065605026"
    password: "249f1433ea7c495a8ed2d49822092bc1"
    accountId: 1
    originator: "MDEV DEMO"
    blacklist: 1
    encoding: 1
    action: 1
    messageType: "N"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

